=== sjmz28/PIAT_2024/Practica1/Fase 2/Responsable.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- SARA JIMÉNEZ MUÑOZ-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.piat.upm.es/responsableSchema"
    xmlns:tns="http://www.piat.upm.es/responsableSchema"
    elementFormDefault="qualified">

    
    <xsd:element name="responsable" type="tns:responsableType"/>

    <xsd:complexType name="responsableType">
        <xsd:sequence> <!-- no importa el orden de aparicion -->

            <xsd:element name="colaboradores"> <!-- es una lista no vacia de elementos por lo que -->
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="colaborador" type="xsd:string" maxOccurs="unbounded"/> <!-- es opcional  -->
                        <xsd:element name="departamento" type="xsd:string" maxOccurs="unbounded"/> <!-- es opcional  -->
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element name="contacto">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="email" type="xsd:string"/>
                        <xsd:element name="uri" type="xsd:anyURI" minOccurs="1"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

        </xsd:sequence>
        <xsd:attribute name="identificadorFisal" type="tns:identificadorFisalType"/>
        
    </xsd:complexType>

    <xsd:simpleType name="identificadorFisalType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Z][0-9]{7}[A-Z]"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== sjmz28/PIAT_2024/Practica1/Fase_1/responsable1.xml
<?xml version="1.0" encoding="UTF-8"?>

<tns:responsable  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             
             xmlns:tns="http://www.piat.upm.es/responsableSchema"
             xsi:schemaLocation="http://www.piat.upm.es/responsableSchema ../Fase_2/Responsable.xsd">

    <tns:colaboradores>
        <tns:colaborador>Sara</tns:colaborador>
        <tns:colaborador>Sara Jimenez </tns:colaborador>
        <tns:colaborador>Sara Jimenez MUÃ±oz</tns:colaborador>
        <tns:departamento>NombreDepartamento1</tns:departamento>
        <tns:departamento>NombreDepartamento2</tns:departamento>
    </tns:colaboradores>
    <tns:contacto>
        <tns:email>correo@gmail.com</tns:email>
        <tns:uri>https://www.paginaweb.com</tns:uri>
    </tns:contacto>

</tns:responsable>
