=== sjmz28/PIAT_2024/Practica1/Fase 2/Robot.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- SARA JIMÉNEZ MUÑOZ-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.piat.upm.es/robotSchema"
    xmlns:tns="http://www.piat.upm.es/robotSchema"
    elementFormDefault="qualified">

    <xsd:element name="robot" type="tns:robotType"/>

    <xsd:complexType name="robotType">
        <xsd:sequence> <!-- secuencia de siguientes elementos -->
            <xsd:element name="funcionalidad" type="tns:funcionalidadType" minOccurs="1"/>
            <xsd:element name="sistemaLimpieza" type="tns:sistemLimpiezaType" minOccurs="1"/>
            <xsd:element name="homologaciones" type="tns:homologacionesType" minOccurs="0"/>
            <xsd:element name="sensores">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="numeroSensores" type="xsd:integer" minOccurs="1"/>
                        <xsd:element name="sensor" type="tns:sensorType" minOccurs="1"/> <!-- lista no vacia de elementos -->
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="actuadores">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="numeroActuadores" type="xsd:integer" minOccurs="1"/>
                        <xsd:element name="actuador" type="tns:actuadorType" minOccurs="1"/> <!-- lista no vacia de elementos -->
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="idRobot" type="tns:idRobotType"/>
    </xsd:complexType>

<!-- *************** Tipos ***************-->
    <xsd:simpleType name="idRobotType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="id-\d{3}"></xsd:pattern>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="funcionalidadType">
        <xsd:restriction base="xsd:string">
            <xsd:maxLength value="256"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="sistemLimpiezaType">
        <xsd:restriction base="xsd:token">
            <xsd:enumeration value="ozono"/>
            <xsd:enumeration value="vapor"/>
            <xsd:enumeration value="ultravioleta"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="homologacionesType">
    <xsd:restriction base="xsd:string">
        <xsd:pattern value="(\w+\s*){0,10}"/>
    </xsd:restriction>
    </xsd:simpleType>

    <!-- ***********************************************************-->
    <!-- ************************** SENSOR *************************-->
    <xsd:complexType name="sensorType">
        <xsd:sequence>
            <xsd:element name="patogeno" type="tns:patogenoType"/>
            <xsd:element name="densidad" type="tns:densidadType"/>
        </xsd:sequence>
        <xsd:attribute name="idSensor" type="tns:idSensorType"></xsd:attribute>    
    </xsd:complexType>


    <xsd:simpleType name="idSensorType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="(a-z){2}(0-9)(A-Z){2}"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="patogenoType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="\w+"/> <!-- una palabra -->
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="densidadType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="\d+\w+\/m2"/><!-- un numero seguido de una palabra y luego el sistema de medida -->
        </xsd:restriction>
    </xsd:simpleType>

<!-- *********************************************************************-->
<!-- ************************** ACTUADORES *******************************-->
<xsd:complexType name="actuadorType">
    <xsd:sequence>
        <xsd:element name="descripcion" type="xsd:string"/>
        <xsd:element name="alcanceActuacion" type="tns:alcanceActuacionType"/>
    </xsd:sequence>
    <xsd:attribute name="idActuador" type="tns:idActuadorType"/> <!-- los atributos siempre al final-->
</xsd:complexType>


<xsd:simpleType name="idActuadorType">
    <xsd:restriction base="xsd:string">
        <xsd:pattern value="(A-Z){2}(0-9){2}"/>
    </xsd:restriction>
</xsd:simpleType>

<xsd:complexType name="alcanceActuacionType">
    <xsd:sequence>
        <xsd:element name="tipoActuacion" type="xsd:string"/>
        <xsd:element name="fechasActuacion" type="tns:fechasActuacionType"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:simpleType name="fechasActuacionType">
    <xsd:list >
        <xsd:simpleType>
            <xsd:union memberTypes="xsd:dateTime xsd:time"/> <!-- para poder admitir dos tipo de elementos en uno-->
        </xsd:simpleType>
    </xsd:list>
</xsd:simpleType>


</xsd:schema>

=== sjmz28/PIAT_2024/Practica1/Fase_1/robot2.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:robot  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             
             xmlns:tns="http://www.piat.upm.es/robotSchema"
             xsi:schemaLocation="http://www.piat.upm.es/robotSchema ../Fase_2/Robot.xsd">
             
    <tns:funcionalidad>La funcionalidad de este robot es ser cute</tns:funcionalidad>
    <tns:sistemaLimpieza>ozono</tns:sistemaLimpieza>
    <tns:homologaciones>homologacion1 homologacion2 homologacion3</tns:homologaciones>
    <tns:sensores>
        <tns:numeroSensores>1</tns:numeroSensores>
        <tns:sensor idSensor="sj2MG">
            <tns:patogeno>patogeno1</tns:patogeno>
            <tns:densidad>5080 bacterias/m3</tns:densidad>
        </tns:sensor>
    </tns:sensores>
    <tns:actuadores>
        <tns:numeroActuadores>7</tns:numeroActuadores>
        <tns:actuador idActuador="JH78">
            <tns:descripcion>esto es una descripcion</tns:descripcion>
            <tns:alcanceActuacion>
                <tns:fechasActuacion>
                2024-01-01T00:00:01 2024-01-01T00:10:02 2024-03-01T00:00:03
                00:00:04 00:00:05 00:00:06 00:00:07 00:00:08 00:00:09 00:00:10
                </tns:fechasActuacion>
                <tns:tipoActuacion>Texto qeu especifica la actuacion</tns:tipoActuacion>
            </tns:alcanceActuacion>
        </tns:actuador>
        <tns:actuador idActuador="JK92">
            <tns:descripcion>esto es una descripcion2</tns:descripcion>
            <tns:alcanceActuacion>
                <tns:fechasActuacion>
                00:00:02 00:00:03 00:00:04 00:00:05 00:00:06 00:00:07 00:00:08 00:00:09 00:00:10
                </tns:fechasActuacion>
                <tns:tipoActuacion>Esto es un texro descriptivo del funcionamiento</tns:tipoActuacion>
            </tns:alcanceActuacion>
        </tns:actuador>
    </tns:actuadores>
</tns:robot>

=== sjmz28/PIAT_2024/Practica1/Fase_1/robot1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:robot  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             
             xmlns:tns="http://www.piat.upm.es/robotSchema"
             xsi:schemaLocation="http://www.piat.upm.es/robotSchema ../Fase_2/Robot.xsd">




    <tns:funcionalidad>La funcionalidad de este robot es ser util pero la cadema de caracteres 
        debe de ser como maximo de 256 caracteres luego voy a poner muchos para ver si se cumple
        *************************************************************************
    </tns:funcionalidad>
    <tns:sistemaLimpieza>ultravioleta</tns:sistemaLimpieza> <!-- ozono, vapor o ultravioleta-->
    <tns:homologaciones>homologacion1 homologacion2 homologacion3 homologacion4 homologacion5
                        homo6 homo7 homo8 homo9 homo10 
    </tns:homologaciones>
    <tns:sensores>
        <tns:numeroSensores>2</tns:numeroSensores>
        <tns:sensor idSensor="ab1CD">
            <tns:patogeno>patogeno1</tns:patogeno>
            <tns:densidad>5000 bacterias/m2</tns:densidad>
        </tns:sensor>
        <tns:sensor idSensor="ab1CZ">
            <tns:patogeno>patogeno2</tns:patogeno>
            <tns:densidad>5080 bacterias/m3</tns:densidad>
        </tns:sensor>
    </tns:sensores>
    <tns:actuadores>
        <tns:numeroActuadores>1</tns:numeroActuadores>
        <tns:actuador idActuador="AC09">
            <tns:descripcion>esto es una descripcion</tns:descripcion>
            <tns:alcanceActuacion>
                <tns:tipoActuacion>Texto qeu especifica la actuacion</tns:tipoActuacion>
                <tns:fechasActuacion>2024-01-02T00:00:01 2024-01-02T00:10:02 2024-03-02T00:00:03
                00:00:04 00:00:05 00:00:06 00:00:07 00:00:08 00:00:09 00:00:10
                </tns:fechasActuacion>
            </tns:alcanceActuacion>
        </tns:actuador>
    </tns:actuadores>
</tns:robot>
